
service: serverless-carlo

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1


functions:
  create-sample:
    handler: Sample/Create/handler.create
    events:
      - http:
          path: sample
          method: POST
          cors: true
  get-sample:
    handler: Sample/Get/handler.get
    events:
      - http:
          path: sample
          method: GET
          cors: true
  update-sample:
    handler: Sample/Update/handler.update
    events:
      - http:
          path: sample
          method: PATCH
          cors: true
  delete-sample:
    handler: Sample/Delete/handler.delete
    events:
      - http:
          path: sample
          method: DELETE
          cors: true
plugins:
  - serverless-offline